language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
 
matrix:
  allow_failures:
    - node_js: "0.11"
 
env:
  - NODE_ENV=test
 
before_script:
  - npm install -g bower
  - npm install
  - bower install
  - "npm start &"