language: node_js
node_js:
  - "5.4.0"

services:
  - mysql

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    
before_script:
  - npm install -g bower
  - bower install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
script: npm test