language: node_js
node_js:
  - "5.4.0"

services:
  - mysql
  
before_script:
  - npm install -g bower
  - bower install

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mysql -e "create database if not exist localdb;" -uroot
  
script: npm test

after_success:
  - npm run codecov